# Script: renv project setup.R 

## Using {renv} package setup environment for this project
library(renv)

# 1. Initialize environment for this specific project 
# Call renv::init() to start using renv in the current project. This will
## Setup project infrastructure
## Discover packages and install them into a project library
## Create a lockfile that records the state of the project

renv::init()

# 2. Run all required scripts. Whilst building the Shiny app I will be installing
#    specific libraries for different types of analysis and shiny app sections building
## Install one or more R packages on this isolated environment for this project.
#  the local cache of pcakges installations is used when possible.

renv::install('pacman')
renv::install('here')
renv::install('tidyverse')
renv::install('janitor')
renv::install('shiny')
renv::install('shinydashboard')

# 3 Check status of your lockfile using renv::status() function:
## status() reports issues caused by inconsistencies across the project lockfile

renv::status()

# 4 After we have confirmed the code works as expected, we use renv::snapshot()
## To record the packages and their sourecs in the lockfile

renv::snapshot()

# 5. To replicate this project in any machine, once all outputs have been created
# restore() > Restore a project's dependencies from a lockfile, as previously generated by snapshot()
# renv::restore()

